# Generated by Django 4.0.5 on 2022-06-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['color']},
        ),
    ]
