# Generated by Django 4.0.5 on 2022-06-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_car_color_alter_car_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['color']},
        ),
    ]
